# The backup will be put in S3://BUCKET/FOLDER/FILENAME-TIMESTAMP.sql.gz
 bucket: queriac
 folder: dumps
 filename: queriac
 AWS_ACCESS_KEY_ID: 1NXMHSQFT0F16WRSJSR2
 AWS_SECRET_ACCESS_KEY: 1y7pu8AEueQkRhbWAUdjHxA+3sL/ppFnO5dMka7m
 email: sikelianos@gmail.com
# email: first@email.com,second@joe.com,third@fred.com 
 smtp_server: localhost
 mysql_password: ereiamJH